### ISSUE TITLE
MSC3886 fails with cors erorr when element and matrix on seperate domains

### ISSUE THREAD

**Issue by SuperSandro2000** [matrix-org/matrix-js-sdk#3168]
I have synapse on matrix.example.com and element on element.matrix.org. When trying to display a qr code in device settings it fails with the following errors:

```
Rendezvous failed: user_cancelled [rageshake.ts:64:12](webpack:///node_modules/matrix-react-sdk/src/rageshake/rageshake.ts)
XHROPTIONShttps://matrix.example.com/_synapse/client/org.matrix.msc3886/rendezvous/01GSV7BHK92640AXXXXXXXXXXX
CORS Preflight Did Not Succeed

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matrix.example.com/_synapse/client/org.matrix.msc3886/rendezvous/01GSV7BHK92640AXXXXXXXXXXX. (Reason: CORS request did not succeed). Status code: (null).

Error whilst doing QR login TypeError: NetworkError when attempting to fetch resource.
```

The requested url returns 404 which is not allowed by cors.

relevant synapse settings:
```yaml
experimental_features:
  msc3882_token_timeout: 5m
  msc3882_ui_auth: true
  msc3886_endpoint: /_synapse/client/org.matrix.msc3886/rendezvous
modules:
- config:
    prefix: /_synapse/client/org.matrix.msc3886/rendezvous
  module: matrix_http_rendezvous_synapse.SynapseRendezvousModule
```
